#! /bin/sh

perl -ne 'next if m%_END_%; s%_(NOUN|CONJ|ADV|DET|ADJ|VERB|ADP|PRT|PRON|NUM|X)%%g; next if m%(\s|^)[^A-Za-z0-9]+(\s|$)%; print;' "$@" | perl -lane 'next unless @F == 9; next unless $F[5] > 1950; $s = join "\t", @F[0..4]; $l ||= $s; if ($l ne $s) { print join "\t", $l, $n; undef $l; undef $n; }; $n+=$F[6]; } { print join "\t", $l, $n if defined $l;'
